### PR TITLE
Add error handling for cloud provider

### PR DESCRIPTION
**Pull request by dav1x**
1. Resolves issue #8
2. Add error handling on providerID.
3. Cast zone toLower for consistency.
4. Tested and works fine.

### CODE REVIEW

**Review by font — APPROVED** [review]
Thanks @dav1x! LGTM.

**Comment by font** [comment]
@dav1x Can you squash your commits for merging?

**Comment by dav1x** [comment]
Done! Thanks

**Review by font — COMMENTED** [review]
Thanks @dav1x!

**Pull request merged**
